In [1]:
import numpy as np
import matplotlib.pyplot as plt

# cargamos los datos

In [39]:

# Ruta al archivo
ajuste_ruta = 'datos/ajuste.txt'
validacion_ruta = 'datos/validacion.txt'

# Leer el archivo y convertirlo a una matriz NumPy
ajuste = np.loadtxt(ajuste_ruta)
validacion = np.loadtxt(validacion_ruta)


[[-0.97979798 -1.81318213]
 [-0.93939394 -2.22997127]
 [-0.8989899  -1.84905143]
 [-0.85858586 -0.79720233]
 [-0.81818182  0.12560892]
 [-0.77777778  0.79992017]
 [-0.73737374  0.87367396]
 [-0.6969697   0.72559319]
 [-0.65656566  0.71784904]
 [-0.61616162  0.82430123]
 [-0.57575758  1.04434198]
 [-0.53535354  1.56805389]
 [-0.49494949  1.30040349]
 [-0.45454545  0.82171008]
 [-0.41414141  0.20985329]
 [-0.37373737 -0.3607258 ]
 [-0.33333333 -0.66649654]
 [-0.29292929 -0.79936444]
 [-0.25252525 -0.98778983]
 [-0.21212121 -1.10814745]
 [-0.17171717 -1.06793953]
 [-0.13131313 -0.96771228]
 [-0.09090909 -0.71824023]
 [-0.05050505 -0.37222851]
 [-0.01010101 -0.09581148]
 [ 0.03030303  0.26664172]
 [ 0.07070707  0.59683875]
 [ 0.11111111  0.77090648]
 [ 0.15151515  0.96866998]
 [ 0.19191919  0.85680926]
 [ 0.23232323  0.77386806]
 [ 0.27272727  0.64384725]
 [ 0.31313131  0.52733484]
 [ 0.35353535  0.25033432]
 [ 0.39393939  0.08603352]
 [ 0.43434343 -0.25338231]
 [ 0.47474747 -0.59781592]
 

# Punto 2

### 2.a

In [86]:
# TODO CORRROBORAR LA RESTA DE COSAS MUY CERCANAS ENTRE SI PARA QUE DE 0

def cml(X, y):
    U, S, VT = np.linalg.svd(X)
    # Crear la matriz diagonal Σ con los valores singulares S
    # print(S)
    print(F"cantidad de elementos de S = {len(S)}")
    # print(S)
    S = np.diag(S)
    
    # print(S)
    S_inv = np.linalg.inv(S)
    # 
    print(f"Len(U): {len(U)} Len(U[0]) {len(U[0])}")
    U = U[:, 0: len(VT)]
    print(f"Len(V): {len(VT.T)} Len(V[0]) {len(VT.T[0])}")
    print(f"Len(S_inv): {len(S_inv)} Len(S_inv[0]) {len(S_inv[0])}")
    vt_s = VT.T @ S_inv
    vt_s_u = vt_s @ U.T
    beta =  vt_s_u @ y
    return beta

def error_cml(X, beta, y):
    # print("X:")
    # print(X)
    # print("beta:")
    # print(beta)
    # print("y:")
    # print(y)
    return np.linalg.norm(X @ beta - y, ord=2)**2

### 2.b

In [8]:
def cml_regularizacion(X, y, l):

    U, S, VT = np.linalg.svd(X)
    print(S)
    # S = S[0 : len(VT), :]
    S2 = S@S
    U = U[:, 0: len(VT)]
    D = np.zeros((len(S), len(S)))
    D = np.fill_diagonal(D, l)
    beta = VT.T @ np.linalg.inv(S2 + D) @ U.T @ y
    
    return beta

### testeo

In [40]:
A = np.array([[-1, -1, 0, 0, 1, 2,2,2],
              [ -1, 0, 0, 1, 0,0,-1, 1],
              [ 1,1,1,1,1,1,1,1]])
y = np.array([-3, -1, 2, -5, -9, 2, 0, 3])
cml(A.T, y)

array([ 1.00000000e+00, -7.77156117e-16, -2.00000000e+00])

# punto 3

### 3.a

##### experimento legendre

In [94]:
def ajuste_legendre(x, y, grado):
    print("legendre:")
    A = np.polynomial.legendre.legvander(x, grado)
    print(f"Len(legendre): {len(A)} Len(legendre[0]) {len(A[0])}")
    return cml(A, y)



def experimento_legendre(x_aj, y_aj, x_val, y_val):
    legendres = []
    errores_ajuste = []
    errores_val = []
    grados = []
    for i in range(1 , len(x_aj)*2+ 1):
        A = np.polynomial.legendre.legvander(x_aj, i)
        beta = cml(A, y_aj)
        errores_ajuste.append(error_cml(A, beta, y_aj))
        # errores_val.append(error_cml(x_val, beta, y_val))
        grados.append(i)

    plt.figure()
    plt.scatter(grados, errores_ajuste, color='b', label=f'errores ajuste')
    plt.scatter(grados, errores_val, color='g', label=f'errores val')

    plt.title('errores')
    plt.xlabel('p')
    plt.ylabel('Performance')
    plt.legend()
    # plt.savefig("performance_de_p_con_k_fijo")
    plt.show()

experimento_legendre(ajuste[:, 0], ajuste[:, 1], validacion[:, 0], validacion[:, 1])

cantidad de elementos de S = 2
[7.07161428 4.12257668]
Len(U): 50 Len(U[0]) 50
Len(V): 2 Len(V[0]) 2
Len(S_inv): 2 Len(S_inv[0]) 2
cantidad de elementos de S = 3
[7.0720841  4.12737479 3.21929669]
Len(U): 50 Len(U[0]) 50
Len(V): 3 Len(V[0]) 3
Len(S_inv): 3 Len(S_inv[0]) 3
cantidad de elementos de S = 4
[7.07257954 4.13116071 3.23250788 2.73278504]
Len(U): 50 Len(U[0]) 50
Len(V): 4 Len(V[0]) 4
Len(S_inv): 4 Len(S_inv[0]) 4
cantidad de elementos de S = 5
[7.07304787 4.13537573 3.24304584 2.75458324 2.40921448]
Len(U): 50 Len(U[0]) 50
Len(V): 5 Len(V[0]) 5
Len(S_inv): 5 Len(S_inv[0]) 5
cantidad de elementos de S = 6
[7.07362601 4.13938317 3.25618336 2.77095686 2.43547693 2.16932194]
Len(U): 50 Len(U[0]) 50
Len(V): 6 Len(V[0]) 6
Len(S_inv): 6 Len(S_inv[0]) 6
cantidad de elementos de S = 7
[7.07414123 4.14477097 3.26907265 2.79332309 2.45085969 2.19735058
 1.9799067 ]
Len(U): 50 Len(U[0]) 50
Len(V): 7 Len(V[0]) 7
Len(S_inv): 7 Len(S_inv[0]) 7
cantidad de elementos de S = 8
[7.07487493 4.149

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 50 is different from 51)

In [ ]:
_