In [10]:
import numpy as np
import matplotlib.pyplot as plt
# import pandas as pd
# import seaborn as sns

# Cálculo de autovectores: Método de la potencia

## Ejercicio 1: Metodo de la potencia

Implementar el método de la potencia considerando algún criterio de parada

In [11]:
import numpy as np

def power_iteration(A, niter=10_000, eps=1e-6):
    """
    Calcula el autovector al autovalor asociado de valor máximo

    Devuelve (a, v) con a autovalor, y v autovector de A

    Arguments:
    ----------

    A: np.array
        Matriz de la cual quiero calcular el autovector y autovalor

    niter: int (> 0)
        Cantidad de iteraciones

    eps: Epsilon
        Tolerancia utilizada en el criterio de parada
    """

    v = np.arange(len(A))
    for i in range(0, niter):
      v = A@v / np.linalg.norm(A@v)
    l =  (v.T @ A @ v) / (v.T @ v)

    return l, v

    """
    TODO: Completar el método de la potencia

    IMPORTANTE: Agreguen algún criterio de parada!
    """


Verifiquemos la implementación un ejemplo conocido:

$$
A = Q^T \begin{pmatrix}
d_1    &0     &0      &0      &\\
0      &d_2   &0      &0      &\\
\vdots &\vdots&\ddots &\vdots &\\
0      &0     &0      &d_n    & \\
\end{pmatrix} Q
$$

con $Q = I - 2 v v^T$, $||v||_2=1$
 la matriz de reflexión que sabemos que es ortogonal

Probemos calcular con el método de la potencia el autovector y autovalor dominante.

In [24]:
D = np.diag([5.0, 4.0, 3.0, 2.0, 1.0])

v = np.ones((D.shape[0], 1))

v = v / np.linalg.norm(v)
print(v)
print(v @ v.T)
# Matriz de Householder
B = np.eye(D.shape[0]) - 2 * (v @ v.T)
print(B)
# Matriz a diagonalizar
M = B.T @ D @ B

print(M)
power_iteration(M)

[[0.4472136]
 [0.4472136]
 [0.4472136]
 [0.4472136]
 [0.4472136]]
[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]
[[ 0.6 -0.4 -0.4 -0.4 -0.4]
 [-0.4  0.6 -0.4 -0.4 -0.4]
 [-0.4 -0.4  0.6 -0.4 -0.4]
 [-0.4 -0.4 -0.4  0.6 -0.4]
 [-0.4 -0.4 -0.4 -0.4  0.6]]
[[ 3.40000000e+00 -1.20000000e+00 -8.00000000e-01 -4.00000000e-01
  -4.16333634e-16]
 [-1.20000000e+00  3.20000000e+00 -4.00000000e-01 -3.88578059e-16
   4.00000000e-01]
 [-8.00000000e-01 -4.00000000e-01  3.00000000e+00  4.00000000e-01
   8.00000000e-01]
 [-4.00000000e-01 -3.88578059e-16  4.00000000e-01  2.80000000e+00
   1.20000000e+00]
 [-1.94289029e-16  4.00000000e-01  8.00000000e-01  1.20000000e+00
   2.60000000e+00]]


(5.0, array([-0.6,  0.4,  0.4,  0.4,  0.4]))

# Ejercicio 2: Metodo de la potencia + Deflación

Implementar método de la potencia + deflación

In [13]:
def eigen(A, num=2, niter=10000, eps=1e-6):
    """
    Calculamos num autovalores y autovectores usando método de la potencia+deflación
    """
    A = A.copy()
    eigenvalues = []
    eigenvectors = np.zeros((A.shape[0], num))
    l = 0
    v = np.arange(0,len(A))
    for i in range(num):
      v_prima = v @ v.T
      c = l* v_prima
      B = A - c
      li, vi = power_iteration(B)
      eigenvalues.append(li)
      eigenvectors[i]=vi
      l = li
    return np.array(eigenvalues), eigenvectors

## Casos de prueba

Matriz Diagonal

In [14]:
D = np.diag(range(10, 0, -1))
print(D)

#%%time prender si se quiere medir el tiempo
l, v = eigen(D,10,niter=1000)
print(l, v)

[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]
[ 9.00000000e+00 -2.56445003e+04  7.30868314e+07 -2.08297470e+11
  5.93647788e+14 -1.69189620e+18  4.82190416e+21 -1.37424269e+25
  3.91659165e+28 -1.11622862e+32] [[0.00000000e+000 1.00000000e+000 1.97626258e-323 9.88131292e-324
  4.94065646e-324 4.94065646e-324 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [3.16172291e-001 3.16184616e-001 3.16196942e-001 3.16209268e-001
  3.16221596e-001 3.16233924e-001 3.16246254e-001 3.16258584e-001
  3.16270916e-001 3.16283248e-001]
 [3.16227785e-001 3.16227781e-001 3.16227777e-001 3.16227773e-001
  3.16227768e-001 3.16227764e-001 3.16227760e-001 3.16227755e-001
  3.16227751e-001 3.16227747e-001]
 [3.

Otra matriz de Householder

In [15]:
N = 10
D = np.diag(range(N, 0, -1))

v = np.ones((D.shape[0], 1))
v = v / np.linalg.norm(v)

# Matriz de Householder
B = np.eye(D.shape[0]) - 2 * (v @ v.T)

M = B.T @ D @ B
# Para todos los eigen el ejemplo anterior de householder.
l, v = eigen(M, N, niter=1000)
print(l,v)

[ 1.00000000e+01 -2.84945003e+04  8.12093313e+07 -2.31446594e+11
  6.59622794e+14 -1.87992496e+18  5.35778614e+21 -1.52696905e+25
  4.35186179e+28 -1.24028061e+32] [[-0.8         0.2         0.2         0.2         0.2         0.2
   0.2         0.2         0.2         0.2       ]
 [ 0.31627769  0.3162666   0.3162555   0.31624441  0.31623332  0.31622222
   0.31621112  0.31620003  0.31618893  0.31617783]
 [ 0.31622775  0.31622775  0.31622776  0.31622776  0.31622776  0.31622777
   0.31622777  0.31622778  0.31622778  0.31622778]
 [ 0.31622777  0.31622777  0.31622777  0.31622777  0.31622777  0.31622777
   0.31622777  0.31622777  0.31622777  0.31622777]
 [ 0.31622777  0.31622777  0.31622777  0.31622777  0.31622777  0.31622777
   0.31622777  0.31622777  0.31622777  0.31622777]
 [ 0.31622777  0.31622777  0.31622777  0.31622777  0.31622777  0.31622777
   0.31622777  0.31622777  0.31622777  0.31622777]
 [ 0.31622777  0.31622777  0.31622777  0.31622777  0.31622777  0.31622777
   0.31622777  0.31

$A.A^T$ y $A^TA$

In [16]:
AT = A @ A.T
TA = A.T @ A
wta, VTA = eigen(AT, num=3, niter=20000, eps=1e-24)
wat, VAT = eigen(TA, num=3, niter=20000, eps=1e-24)
assert(np.allclose(wat,wta))

NameError: name 'A' is not defined

# Ejercicio 3: Velocidad de convergencia

* Graficar, para la matriz M definida abajo, los valores de la sucesión {$\lambda^{k}$} del autovalor dominante. Considerar, si fuera necesario, extender el método implementado anteriormente para obtener la suecesión.

In [ ]:
D = np.diag([5.0, 4.0, 3.0, 2.0, 1.0])

v = np.ones((D.shape[0], 1))

v = v / np.linalg.norm(v)

# Matriz de Householder
B = np.eye(D.shape[0]) - 2 * (v @ v.T)

# Matriz a diagonalizar
M = B.T @ D @ B

power_iteration(D,1000)

(4.0,
 array([0.00000000e+000, 1.00000000e+000, 2.30299708e-125, 2.79979086e-301,
        0.00000000e+000]))

In [ ]:
...
## COMPLETAR

**Recordemos que**:

Sea ${x_k}$ k ∈ N una sucesión tal que:

$$lim_{k→∞} x_k = x^*$$

Decimos que ${x_k}$ k ∈ N tiene orden de convergencia $p$ si:

$$lim_{k→∞} \frac{|x_{k+1} − x^∗|}{ (|x_k − x^∗ |)^p} =  c > 0 $$



Existen otras formas de definir la noción de velocidad de convergencia como:

Sea ${\alpha_n}$ convergente a $\alpha$. Sea ${\beta_n}$ convergente a 0.

Decimos que ${\alpha_n}$ tiene orden de convergencia $O(\beta_n)$ (o que αn converge tan rápido como $\beta_{n}$) si existe:

 c > 0 tal que $|\alpha_n − \alpha| ≤ c\beta_n$ para todo
n suficientemente grande.




* Analizar la velocidad de convergencia para la sucesión {$\lambda^{k}$} del autovalor dominante.
Considerar, si fuera necesario, extender el método implementado anteriormente para obtener los errores $|\lambda^{k} - \lambda^*|$ (utilizar la segunda definición de velocidad de convergencia)

In [ ]:
...


Analizar la velocidad de convergencia de la sucesión {$v^{k}$}) al autovector dominante

**Imporante: ¿Contra que vector comparamos?**

* En algunos casos podemos no conocer el vector en cuestión.
* Además para el caso de autovalores repetidos, no sabemos exactamente a que combinación del autoespacio cae el vector de la sucesión.



*Obs:Para este caso particular, la convergencia al autovector dominante $e_1$ se da como esperamos*

In [ ]:
...

La forma sugerida en el tp, que evita esos problemas, es considerar $$ ||Av -\lambda v||$$

* Graficar la sucesión de tales errores y comparar.

In [ ]:
...

# Ejercicio 4:

Considerar matrices aleatorias construidas con "el truco de Householder" con los auotvalores dados por $(10,7.75,5.5,3.25,1)$.

Reportar y analizar el error $|| Av - \lambda v ||$ obtenido para cada autovector fijando 300 iteraciones del método de la potencia (sin método de corte).

Recordar mostrar alguna noción de centralidad y dispersión para cada grupo de mediciones.

In [ ]:
reps = ...

eigen_errors = []
niters = []

e = 0.01
for r in reps:

  D = np.diag(np.linspace(1,10,5))
  v = ...
  v = v / np.linalg.norm(v)

  # Matriz de Householder
  B = np.eye(D.shape[0]) - 2 * (v @ v.T)

  # Matriz a diagonalizar
  M = B.T @ D @ B

  l, V, errors = eigen(M,5,niter=300,eps=1e-200)

  eigen_errors.append(...)

# PLOT
...

# Ejercicio 5:

Considerar matrices aleatorias construidas con "el truco de Householder" con los auotvalores dados por $[2, 2-e, 1.9, 1.9-e, 1.8]$ siendo $e = 0.01$.

Reportar y analizar la cantidad de iteraciones obtenido para cada autovector habilitando el método de corte (ajsutando niter y eps de manera que el allclose pase).  

Recordar mostrar alguna noción de centralidad y dispersión para cada grupo de mediciones.

In [ ]:
reps = range(50)

eigen_errors = []
niters = []
niters = []
e = 0.01
for r in reps:
  D = np.diag([2, 2-e, 1.9, 1.9-e, 1.8]).astype(np.float64)
  print(D)
  v = 4*np.random.randn(D.shape[0], 1)
  v = v / np.linalg.norm(v)

  # Matriz de Householder
  B = np.eye(D.shape[0]) - 2 * (v @ v.T)

  # Matriz a diagonalizar
  M = B.T @ D @ B

  l, V, errors = eigen(M,4,niter=...,eps=...)
  n = []
  for er in errors[3]:
    n.append(len(er))
  niters.append(n)
  #eigen_errors.append(np.array(errors[3])[:,-1])
  #niters.append(len(e))


  for i in range(len(l)-1):
    assert(np.allclose(M@V[:,i], l[i] * V [:,i], atol=1e-6))

